@api2 = http://localhost:5000/diccionario
### Get all users no admins
GET http://localhost:3000/getUsersNoAdmin

### Post a new user
POST http://localhost:3000/createUser
Content-Type: application/json

{
    "Nombre": "Carlos",
    "Apellido": "Salinas",
    "Correo": "A01283585@tec.mx",
    "Contrasena": "12345",
    "Puesto": "Documentacion"
}

### Get an specific user to login
POST http://localhost:3000/postUserLogin
Content-Type: application/json

{
    "Correo": "A01283642@tec.mx",
    "Contrasena": "123457"
}

### Get an specific user by id 
GET http://localhost:3000/getUserByID/1

### Delete an specific user by id 
DELETE http://localhost:3000/deleteUserByID/7

### Update user by email and password
PUT http://localhost:3000/updateUserByID/A01283642@tec.mx/123457
Content-Type: application/json

{
    "NuevaContrasena": "1234579"
}

### Get registros usuario especifico
GET http://localhost:3000/getRecordUser/2

### Post a new registro
POST http://localhost:3000/createRecord
Content-Type: application/json

{
    "UsuarioID": 2,
    "Fecha_Calculo": "2021-01-01",
    "Fecha_Inicio": "2021-03-01",
    "Fecha_Fin": "2021-03-09",
    "Nombre_Actividad": "Actividad 2",
    "Descripcion": "zwesxdrcftvgybhunijmok vctybuin",
    "Resumen": "ubinjomkp asff",
    "Dias": 5
}


### Get all words from diccionario
GET {{api2}}
